### ISSUE TITLE
外国人が日本語の.hspファイルを文字化けせずにエンコードできるように、UTF-8のサポートを追加する

### ISSUE THREAD

**Issue by Kawaxte** [honobonosun/vscode-language-hsp3#48]
SHIFT-JISでエンコードされた.hspファイルをアップロードすると、GitHubはそのファイルをUTF-8として再エンコードし、すべての外国文字を文字化けさせてしまいます。

これは大きな見落としで、GitHubが第一の責任を負っているようです。ユーザーが二つのエンコーダーを切り替えられるようにすべきです。

**Comment by honobonosun** [comment]
Kawaxte様、イシュー投稿ありがとうございます。

説明を注意深く読みましたが、何に対して問題なのかを特定することができませんでした。

以下の情報を補足いただければ幸いです。

- イシュータイトルについて
  - UTF-8サポートをどれに対して追加したいのか。
- 「ユーザーが二つのエンコーダーを切り替えられるようにすべきです。」とは、どれに対してどのように切り替えたいのか。

上記を踏まえて、現状可能な限り回答させていただきます。

## UTF-8対応について

VSCode拡張機能"vscode-language-hsp3"のUTF-8対応についてですが、対応済みです。だだし、コンパイルツールなどの外部ツールは動作要件が別です。コンパイルツールはVSCodeではないからです。"Run HSP program"を使用するには、コンパイルツールの動作環境を確認してください。

HSP3のUTF-8対応については、hsp3utfのドキュメントが参考になるかもしれません。

https://www.onionsoft.net/hsp/v36/doclib/hsp3utf.txt

開発環境に同梱されている"sample\\hsp3utf"ディレクトリのサンプルプログラムも参考になるかもしれません。

## GitHub.com上での文字化けについて

下記リンクは、Shift_JISファイルのプルリクエストです。そちらのブラウザで文字化けは起こりますか？

https://github.com/honobonosun/encode-test/pull/1/files#diff-c21122d4ec83d83735f864be3b3b9a0e3c0e7ded8eb95a0a367b57463bfc9619

私は再読み込み（F5）することで文字化けが解決することを確認できました。

<img width="611" alt="image" src="https://github.com/honobonosun/vscode-language-hsp3/assets/15817383/66b34126-2ba4-4ddb-8759-586adaa7ba94">

（HSPファイルがShift_JISだけなら、このサイトが参考になるかもしれません。 https://crystalmark.info/ja/2021/02/14/git-utf16/ ）

Shift_JISのファイル差分を正常に表示させたい場合、GitHub.comのサポートに連絡した方がよいと思われます。ここは、"vscode-language-hsp3"の問題トラッカーなので、Gitと、GitHub.comに関するサポートは承れません。恐れ入りますが、関係各所にお願い申し上げます。

## エンコーダーの切り替えについて

VSCode拡張機能は、VSCodeで編集するエディタの文字エンコードを取得、設定するAPIが実装されない限り、ファイルの内容に応じて文字エンコードを適切に切り替える機能は実装できません。

## Shift_JISのファイルをUTF-8へエンコードする方法

VSCodeには、ファイルのエンコードを変更する機能が備わっています。

1. VSCodeで文字エンコード（charset）を変更するファイルを開きます。
2. 開いたファイルが文字化けしないように、正しいエンコードで開いてください。文字化けした場合、ステータスバーから修正できます。（もしくは、コマンドパレット"Change File Encoding"の、"Reopen with Encoding"でも行えます。）
3. コマンドパレット"Change File Encoding" から、"Save with Encoding"を使用して、ご希望のUTF-8を選択、決定するします。
4. VSCodeによってファイルの文字エンコードが変換、保存されます。

iconvや、nkfコマンドが、ターミナルで使用できるのであれば、BATファイルを用意して使用する方が簡単でしょう。

> [!NOTE]
> Shift_JISのHSPソースファイルをUTF-8へ変換した後、プログラム実行に問題が起こる場合、おそらく、そのプログラムは文字列がShift_JISであることを前提に処理しているはずです。その場合は、手作業でプログラムを修正するしかありません。これに関しては、近道はありません。

この返信がお役に立てれば幸いです。

**Comment by Kawaxte** [comment]
> UTF-8サポートをどれに対して追加したいのか。
通常、.hspファイルが対象です。

> 私は再読み込み（F5）することで文字化けが解決することを確認できました。
信じられない！これはプレビューモードなんだけど、以前[このプロジェクト](https://github.com/Kawaxte/OpenShifter)の.hspファイルをアップロードしたとき、ひどいフォーマットUTF-8で保存され続けて、外国語の記号が全部文字化けしていたんだ。その後、``#include "hsp3utf.as`` が必要なことに気づき、最終的にファイルは文字化けしていないエンコードされたファイルとしてアップロードされました。

> VSCode拡張機能"vscode-language-hsp3"のUTF-8対応についてですが、対応済みです。だだし、コンパイルツールなどの外部ツールは動作要件が違います。コンパイルツールはVSCodeではないからです。"Run HSP program"を使用するには、コンパイルツールの動作環境を確認してください。
私はこの言語がどのように機能するのかあまり詳しくないので、HSP3コードエグゼキュータのUTF-8バリアントを実行する方法がよくわからない。OpenHSPリポジトリから最新の "hsp36 "をダウンロードした。

あなたの指示に従ってVSCodeでUTF-8にエンコードすると、"[continue]"の中で "critical error "が発生して、突然ファイルの実行が止まってしまいます。よくわからない。

**Comment by honobonosun** [comment]
補足情報から、VSCode拡張機能"vscode-language-hsp3"のイシューは解決したと判断します。

ここは、"vscode-language-hsp3"の為の問題トラッカーです。

貴方だけの問題を私に持ち込まないでください。

このイシューは役目を終えたため、クローズします。
